services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
      - "127.0.0.1:443:443" # LocalStack HTTPS Gateway (Pro)
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}
      - LAMBDA_LOG_LEVEL=DEBUG
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=microurl_default
      - LAMBDA_DOCKER_FLAGS=--env AWS_LAMBDA_RUNTIME_API=$${LOCALSTACK_RUNTIME_ENDPOINT}

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:
        aliases:
          - micro.url

networks:
  default:
    driver: bridge